### ISSUE TITLE
Unable to generate Serenity-bdd HTML report

### ISSUE THREAD

**Issue by nshagin** [serenity-js/serenity-js#1020]
Running my scripts and at the end 'serenity-bdd run --features ./features' throwing Unable to load cache item error messages.
Can anyone help me with this?

I am using Java version: 16.0.1
Also, Photographer is not taking any photos into the given folder path,only json report is generating.
```
    serenity: {
        runner: 'cucumber',
        crew: [
            ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
            ConsoleReporter.forDarkTerminals(),
            Photographer.whoWill(TakePhotosOfInteractions),     // or Photographer.whoWill(TakePhotosOfFailures),
            new SerenityBDDReporter(),
        ]
        //outputDirectory: `${process.cwd()}/target/site/serenity/`
    },
```
Logs:
```
[report] INFO: An exception was caught and reported. Message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineCla
ss(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4d405ef7
[report] java.lang.IllegalStateException: Unable to load cache item
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
[report]        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
[report]        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
[report]        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
[report]        at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:69)
[report]        at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:327)
[report]        at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:135)
[report]        at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:105)
[report]        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
[report]        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:356)
[report]        at com.google.inject.spi.Elements.getElements(Elements.java:104)
[report]        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
[report]        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
[report]        at com.google.inject.Guice.createInjector(Guice.java:87)
[report]        at com.google.inject.Guice.createInjector(Guice.java:69)
[report]        at com.google.inject.Guice.createInjector(Guice.java:59)
[report]        at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:27)
[report]        at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:20)
[report]        at net.thucydides.core.requirements.FileSystemRequirementsService.<init>(FileSystemRequirementsService.java:20)
[report]        at net.thucydides.core.requirements.FileSystemRequirements.<init>(FileSystemRequirements.java:24)
[report]        at net.serenitybdd.cli.reporters.RequirementsStrategy.forDirectory(RequirementsStrategy.java:11)
[report]        at net.serenitybdd.cli.reporters.CLIAggregateReportGenerator.generateReportsFrom(CLIAggregateReportGenerator.java:50)
[report]        at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:56)
[report]        at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
[report]        at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
[report] Caused by: java.lang.ExceptionInInitializerError
[report]        at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:104)
[report]        at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
[report]        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
[report]        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
[report]        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
[report]        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
[report]        ... 27 more
[report] Caused by: com.google.inject.internal.cglib.core.$CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lan
g.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unna
med module @4d405ef7
[report]        at com.google.inject.internal.cglib.core.$ReflectUtils.defineClass(ReflectUtils.java:464)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:339)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
[report]        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory$Generator.create(KeyFactory.java:221)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:174)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:157)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:149)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:145)
[report]        at com.google.inject.internal.cglib.core.$MethodWrapper.<clinit>(MethodWrapper.java:23)
[report]        ... 38 more
[report] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.se
curity.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4d405ef7
[report]        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[report]        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[report]        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[report]        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[report]        at com.google.inject.internal.cglib.core.$ReflectUtils$1.run(ReflectUtils.java:61)
[report]        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
[report]        at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:52)
[report]        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
[report]        ... 35 more
[report]
[report] Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
[report]        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
[report]        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[report]        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
[report]        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
[report]        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
[report]        at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
[report]        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
[report]        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
[report]        at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:606)
[report]        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:943)
[report]        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863)
[report]        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:300)
[report]        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:231)
[report]        at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:949)
[report]        at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48)
[report]        at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60)
[report]        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:135)
[report]        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
[report]        at com.google.inject.Guice.createInjector(Guice.java:87)
[report]        at com.google.inject.Guice.createInjector(Guice.java:69)
[report]        at com.google.inject.Guice.createInjector(Guice.java:59)
[report]        at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:27)
[report]        at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:20)
[report]        at net.thucydides.core.requirements.FileSystemRequirementsService.<init>(FileSystemRequirementsService.java:20)
[report]        at net.thucydides.core.requirements.FileSystemRequirements.<init>(FileSystemRequirements.java:24)
[report]        at net.serenitybdd.cli.reporters.RequirementsStrategy.forDirectory(RequirementsStrategy.java:11)
[report]        at net.serenitybdd.cli.reporters.CLIAggregateReportGenerator.generateReportsFrom(CLIAggregateReportGenerator.java:50)
[report]        at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:56)
[report]        at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
[report]        at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
[report] Caused by: java.lang.IllegalStateException: Unable to load cache item
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
[report]        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
[report]        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
[report]        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
[report]        at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:49)
[report]        at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:156)
[report]        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:94)
[report]        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
[report]        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
[report]        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
[report]        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
[report]        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
[report]        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
[report]        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
[report]        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
[report]        ... 29 more
[report] Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
[report]        at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:104)
[report]        at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
[report]        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
[report]        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
[report]        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
[report]        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
[report]        ... 46 more
```

**Comment by jan-molak** [comment]
Hi @nshagin! The `java.lang.IllegalStateException` feels like an issue with the Serenity BDD CLI module, available at https://github.com/serenity-bdd/serenity-cli. Would you mind adding a ticket there so that it can be tracked and addressed? 
Thanks!

The issue with screenshots not being generated is most likely unrelated to that.
Could you please advise what Serenity/JS modules you're using in your framework? In particular, are you using `@serenity-js/protractor` or `@serenity-js/webdriverio` for Web integration?
Also, do your tests follow the Screenplay pattern? The `Photographer` requires `Actor`s to work.

Thanks!

**Comment by nshagin** [comment]
Thank you for your response.
1. The given respository https://github.com/serenity-bdd/serenity-cli. is displayed as _This repository has been archived by the owner. It is now read-only._ not able to raise as an issue there. Could you please update it so that I can add it to it?
![image](https://user-images.githubusercontent.com/38897344/135365120-ef77cfbc-3f2c-4d3f-a45c-a78b3c324030.png)

2. Please find the versions for serenity-js used in package.json
  "devDependencies": {
    "@serenity-js/assertions": "^2.29.6",
    "@serenity-js/console-reporter": "^2.29.6",
    "@serenity-js/core": "^2.29.6",
    "@serenity-js/cucumber": "^2.29.6",
    "@serenity-js/mocha": "^2.29.6",
    "@serenity-js/protractor": "^2.29.6",
    "@serenity-js/serenity-bdd": "^2.29.6",
    "serenity-cli": "^0.11.1",
    "serenity-js": "^1.10.13",
Framework : Protractor - Cucumber
I think I am missing Actor code. 
Since I am using protractor browser browser.driver.get(appUrl); in the framework. May be thats why its not taking screenshots.
I am new to Serenity-JS so I will just go through the document and see how to implement PRotractor-java script code for Actor.  Could I please approach you if I am not able to do that?
Thank you so much.

**Comment by nshagin** [comment]
@jan-molak I have raised a ticket under https://github.com/serenity-bdd/serenity-core. Thank you.
Regards,
Neema
