### ISSUE TITLE
Jasmine's beforeAll strange behavior when using async block 

### ISSUE THREAD

**Issue by manuelfidalgo** [serenity-js/serenity-js#1162]
When using Serenity/JS with Jasmine & wdio, I have seen the following problem:
If you use an actor with BrowseTheWeb ability inside an async/await block in the beforeAll, some other tests are not executed.

**Example**
Imagine you have the following Actors class:

```js
export class Actors implements Cast {
  prepare(actor: Actor): Actor {
    switch (actor.name) {
      case ACTOR.CAN_BROWSE:
        return actor.whoCan(
          BrowseTheWeb.using(browser),
          TakeNotes.usingASharedNotepad()
        )

      case ACTOR.CANNOT_BROWSE:
        return actor.whoCan(TakeNotes.usingASharedNotepad())

      default:
        throw new Error(
          `The actor called ${actor.name} is not one of the recognised personas.`
        )
    }
  }
}
```
And the following test suite:
```js
describe(`Failing Suite: test #2 does not get executed`, () => {
  beforeAll(async function () {
    //unless we remove this await, test #2 and afterAll will never be executed
    await actorCalled(ACTOR.CAN_BROWSE).attemptsTo(
      Log.the(`Serenity BeforeAll: Hello`)
    )
  })

  it('Test #1', function () {
    console.log('Serenity test #1')
  })

  it('Test #2', function () {
    console.log('Serenity test #2')
  })
})
```
The second test is not executed:
![image](https://user-images.githubusercontent.com/7713247/159932659-51645db1-e30e-447e-a83b-5e680d4e4f9a.png)

This does not happen if the actor does not have that ability or you remove the async word.

```js
describe(`Suite working fine`, () => {
  beforeAll(async function () {
    //unless we remove this await, test #2 and afterAll will never be executed
    await actorCalled(ACTOR.CANNOT_BROWSE).attemptsTo(
      Log.the(`Serenity BeforeAll: Hello`)
    )
  })

  it('Test #1', function () {
    console.log('Serenity test #1')
  })

  it('Test #2', function () {
    console.log('Serenity test #2')
  })
})
```

![image](https://user-images.githubusercontent.com/7713247/159947016-24f980c0-9404-4852-ae71-f835c544af5c.png)

You can access the full working example at https://github.com/manuelfidalgo/jasmine-serenity

Thanks in advance!

**Comment by viper3400** [comment]
Strange, I tried to reproduce this but was not able to. My output:

```PowerShell
PS C:\tmp\jasmine-serenity> npm test

> jasmine-serenity@0.0.1 test
> wdio run wdio.conf.ts


Execution of 2 workers started at 2022-03-26T11:37:06.135Z

Failed to connect to selenium. Attempts left: 25 
 connect ECONNREFUSED 127.0.0.1:4444
Failed to connect to selenium. Attempts left: 20 
 connect ECONNREFUSED 127.0.0.1:4444
[0-0] RUNNING in chrome - C:\tmp\jasmine-serenity\test\specs\failing.spec.ts
[0-1] RUNNING in chrome - C:\tmp\jasmine-serenity\test\specs\working.spec.ts
[0-0] Serenity test #1
[0-1] Serenity test #1
[0-0] Serenity test #2
[0-1] Serenity test #2
[0-0] PASSED in chrome - C:\tmp\jasmine-serenity\test\specs\failing.spec.ts
[0-1] PASSED in chrome - C:\tmp\jasmine-serenity\test\specs\working.spec.ts

 "spec" Reporter:
------------------------------------------------------------------
[chrome 99.0.4844.82 windows #0-0] Running: chrome (v99.0.4844.82) on windows
[chrome 99.0.4844.82 windows #0-0] Session ID: 4e6126e951dbef6f79b7c8518264b6e8
[chrome 99.0.4844.82 windows #0-0]
[chrome 99.0.4844.82 windows #0-0] » \test\specs\failing.spec.ts
[chrome 99.0.4844.82 windows #0-0] Failing Suite: test #2 does not get executed
[chrome 99.0.4844.82 windows #0-0]    ✓ Test #1
[chrome 99.0.4844.82 windows #0-0]    ✓ Test #2
[chrome 99.0.4844.82 windows #0-0]
[chrome 99.0.4844.82 windows #0-0] 2 passing (588ms)
------------------------------------------------------------------
[chrome 99.0.4844.82 windows #0-1] Running: chrome (v99.0.4844.82) on windows
[chrome 99.0.4844.82 windows #0-1] Session ID: 1dcdaa7c4e14d624660a60c1a5f2009b
[chrome 99.0.4844.82 windows #0-1]
[chrome 99.0.4844.82 windows #0-1] » \test\specs\working.spec.ts
[chrome 99.0.4844.82 windows #0-1] Suite working fine
[chrome 99.0.4844.82 windows #0-1]    ✓ Test #1
[chrome 99.0.4844.82 windows #0-1]    ✓ Test #2
[chrome 99.0.4844.82 windows #0-1]
[chrome 99.0.4844.82 windows #0-1] 2 passing (588ms)


Spec Files:      2 passed, 2 total (100% completed) in 00:00:16 
```
I got an error first when running `npm test` first caused by a missing dependency to `@wdio/selenium-standalone-service`,  so I installed it (`npm install -D @wdio/selenium-standalone-service`). But actually, the error did not stop the test from running and the test itself ran fine. So I assume there is no dependency to this.

What I changed as well was the the ` specs: ["./test/specs/**/*.spec.ts"]` in your `wdio.conf`, because this pointed just to `*.ts` files. This would include your `actors.ts` into the test run, but this would be skipped anyway, as it's no valid spec file at all. So no suspect here as well.

Okay, so what over dependencies do we have here? I run the test on my local Windows machine:
* Windows 11 Version 21H2 (Build 22000.556)
* Node 16.14.2 ( I tried 14.18.2 as well, same result)
* Npm 7.18.1
* Chrome 99.0.4844.82

What is your node version and what about the Linux system, your test are executed at?

**Comment by manuelfidalgo** [comment]
Hi @viper3400 
thanks for looking at the issue!
The `npm test` script does not use Serenity (just wdio): I used it to check that the issue was not in the wdio package.
In order to see the problem with Serenity, you need to run `npm run test-serenity`
Sorry for the misunderstood

**Comment by viper3400** [comment]
@manuelfidalgo , ahh, thanks. Sorry, did not see the other npm script. So with this setup I was able to reproduce the issue. I did some enhanced tests and have some findings I still have to double check. Is this blocking you?

**Comment by jan-molak** [comment]
Hey @manuelfidalgo

So it seems like `BrowseTheWeb` might have been a red herring and the actual error is thrown by the `SerenityBDDReporter`.

If you add the `StreamReporter` to the `crew`:
```
new StreamReporter(fs.createWriteStream(`./events-${ new Date() }.log`)),
```
it logs the following error:
```
TypeError: Cannot read properties of undefined (reading 'equals')
    at node_modules/@serenity-js/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/EventQueues.ts:52:79\n    
    at Array.find (<anonymous>)\n    
    at EventQueues.queueIdFor (node_modules/@serenity-js/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/EventQueues.ts:52:51)
    at EventQueues.shouldStartNewQueueFor (node_modules/@serenity-js/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/EventQueues.ts:37:39)
    at EventQueues.enqueue (node_modules/@serenity-js/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/EventQueues.ts:18:18)
    at SerenityBDDReporter.notifyOf (node_modules/@serenity-js/serenity-bdd/src/stage/crew/serenity-bdd-reporter/SerenityBDDReporter.ts:93:30)
    at node_modules/@serenity-js/core/src/stage/StageManager.ts:25:59
    at Array.forEach (<anonymous>)
    at StageManager.notifyOf (node_modules/@serenity-js/core/src/stage/StageManager.ts:25:26)
    at Stage.announce (node_modules/@serenity-js/core/src/stage/Stage.ts:177:22)
```
When we remove `SerenityBDDReporter` from the `crew`, we get correct result:
```
 "spec" Reporter:
------------------------------------------------------------------
[Chrome Headless 99.0.4844.83 darwin #0-0] Running: Chrome Headless (v99.0.4844.83) on darwin
[Chrome Headless 99.0.4844.83 darwin #0-0] Session ID: 4252d1ee-3b09-4c3b-a453-b377167dd445
[Chrome Headless 99.0.4844.83 darwin #0-0]
[Chrome Headless 99.0.4844.83 darwin #0-0] » /test/specs/working.spec.ts
[Chrome Headless 99.0.4844.83 darwin #0-0] Suite working fine
[Chrome Headless 99.0.4844.83 darwin #0-0]    ✓ Test #1
[Chrome Headless 99.0.4844.83 darwin #0-0]    ✓ Test #2
[Chrome Headless 99.0.4844.83 darwin #0-0]
[Chrome Headless 99.0.4844.83 darwin #0-0] 2 passing (74ms)
------------------------------------------------------------------
[Chrome Headless 99.0.4844.83 darwin #0-1] Running: Chrome Headless (v99.0.4844.83) on darwin
[Chrome Headless 99.0.4844.83 darwin #0-1] Session ID: 499bc64a-4a0e-4345-b8c7-007681a8ecc0
[Chrome Headless 99.0.4844.83 darwin #0-1]
[Chrome Headless 99.0.4844.83 darwin #0-1] » /test/specs/failing.spec.ts
[Chrome Headless 99.0.4844.83 darwin #0-1] Failing Suite: test #2 does not get executed
[Chrome Headless 99.0.4844.83 darwin #0-1]    ✓ Test #1
[Chrome Headless 99.0.4844.83 darwin #0-1]    ✓ Test #2
[Chrome Headless 99.0.4844.83 darwin #0-1]
[Chrome Headless 99.0.4844.83 darwin #0-1] 2 passing (482ms)
```
It seems like there's a bug somewhere between the Jasmine adapter and `SerenityBDDReporter`.

I'll need to debug it.

Thanks for the repro!

**Comment by manuelfidalgo** [comment]
wow! thanks guys, that's awesome!

**Comment by jan-molak** [comment]
No worries, thanks for finding the bug and providing a repro :-)
@viper3400 - thanks for showing Manuel the example projects and investigating the issue!
