### ISSUE TITLE
Cucumber Window resize return error: disconnected: unable to connect to renderer

### ISSUE THREAD

**Issue by sabau** [serenity-js/serenity-js#124]
I have a working test set with Mocha, and translating it into Cucumber.
Some steps needs resizing, to test and I had no problems with Mocha 
A lot of other commands works fine (the translation is still WIP) but I can't resize in run time.
I fixed by adding a capability to every browser: '--window-size=1280,740' but I need the ability to change screen size.

 I added an optional step:     

    this.Then(/^([\w]+) Set Fullscreen$/, (actor: string) => {
        return stage.theActorCalled(actor).attemptsTo(
            ResizeBrowserWindow.toMaximum()
        );
    });

If I insert this step into my feature files I get:

    WebDriverError: disconnected: unable to connect to renderer

More verbose:

    1) Scenario: Open report page - src\Reporting.feature:4
       Step: Then IFS Set Fullscreen - src\Reporting.feature:7
       Step Definition: node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:47
       Message:
         WebDriverError: disconnected: unable to connect to renderer
           (Session info: chrome=62.0.3202.94)
           (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)
             at WebDriverError (D:\git\QA\bdd\node_modules\selenium-webdriver\lib\error.js:27:5)
             at Object.checkLegacyResponse (D:\git\QA\bdd\node_modules\selenium-webdriver\lib\error.js:505:15)
             at parseHttpResponse (D:\git\QA\bdd\node_modules\selenium-webdriver\lib\http.js:509:13)
             at doSend.then.response (D:\git\QA\bdd\node_modules\selenium-webdriver\lib\http.js:440:13)
             at process._tickCallback (internal/process/next_tick.js:109:7)
         From: Task: WebDriver.manage().window().maximize()
             at thenableWebDriverProxy.schedule (D:\git\QA\bdd\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
             at Window.maximize (D:\git\QA\bdd\node_modules\selenium-webdriver\lib\webdriver.js:1597:25)
             at MaximiseBrowserWindow.performAs (D:\git\QA\bdd\node_modules\serenity-js\src\serenity-protractor\screenplay\interactions\resize_browser_window.ts:12:57)
             at D:\git\QA\bdd\node_modules\@serenity-js\core\src\screenplay\actor.ts:112:43
             at process._tickCallback (internal/process/next_tick.js:109:7)
         From: Task: <anonymous>
             at World.stepWrapper (D:\git\QA\bdd\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:72:18)
             at World.stepWrapper (D:\git\QA\bdd\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:104:32)
             at World.arity1 (eval at <anonymous> (D:\git\QA\bdd\node_modules\util-arity\arity.js:22:24), <anonymous>:3:41)
             at _combinedTickCallback (internal/process/next_tick.js:73:7)
             at process._tickCallback (internal/process/next_tick.js:104:9)

I'm running it under Windows 7 with Node 6.11.4
Those are the related dependencies:

    "@types/chai": "^4.0.4",
    "@types/chai-as-promised": "0.0.31",
    "@types/cucumber": "1.3.1",
    "@types/mocha": "^2.2.43",
    "chai": "^4.1.2",
    "chai-as-promised": "7.0.0",
    "cucumber": "1.3.2",
    "mocha": "^3.5.3",
    "mocha-typescript": "^1.1.9",
    "protractor": "5.1.2",
    "serenity-js": "^1.9.2",

**Comment by jan-molak** [comment]
Would you be able to create a minimalistic test case using the [cucumber seed](https://github.com/serenity-js/seed-cucumber) so I can try to reproduce the issue?

Thanks!
Jan

**Comment by sabau** [comment]
Hi Jan,
Ok I've just pushed the forked version of seed-cucumber.
I forked the repo as the change I made is not supposed to stay there: [sabau/seed-cucumber](https://github.com/sabau/seed-cucumber)

The root cause is switching from SeleniumServerJar to SeleniumAddress, in this scenario it breaks.
 I was able to make it work on my project. The cucumber versions were different but aligning them didn't solve the problem. The solution was     
// seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
    seleniumServerJar: seleniumJar,

**Comment by jan-molak** [comment]
Thanks for investigating that, @sabau! Do you think we need to change anything in Serenity/JS or the seed projects then?

**Comment by jan-molak** [comment]
The seed projects have been superseded by [serenity-js-cucumber-protractor-template](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) and [serenity-js-jasmine-protractor-template](https://github.com/serenity-js/serenity-js-jasmine-protractor-template) and will be archived soon (#339)
