### ISSUE TITLE
Serenity/JS 3.0 - protractor-cucumber example broken

### ISSUE THREAD

**Issue by lucieneven** [serenity-js/serenity-js#1491]
Hello all,

I have a similar problem like #954, but the error comes from protractor-cucumber example.

To reproduce:

- Start with a clean repo, by downloading the latest build. 
- npm i to install all dependencies.
- npm run test in folder 'serenity-js/examples/protractor-cucumber'
- We'll get the following error:

```
[test:acceptance] > @examples/protractor-cucumber@3.0.0 test:acceptance /Users/ruwang/workcenter/serenity-js_v3/examples/protractor-cucumber
[test:acceptance] > protractor ./protractor.conf.js
[test:acceptance] 
[test:acceptance] [18:45:33] I/launcher - Running 1 instances of WebDriver
[test:acceptance] [18:45:33] I/direct - Using ChromeDriver directly...
[test:acceptance] [18:45:34] E/launcher - Error: /Users/ruwang/workcenter/serenity-js_v3/examples/protractor-cucumber/features/support/setup.ts:1
[test:acceptance] import { setDefaultTimeout } from '@cucumber/cucumber';
[test:acceptance] ^^^^^^
[test:acceptance] 
[test:acceptance] SyntaxError: Cannot use import statement outside a module
[test:acceptance]     at wrapSafe (internal/modules/cjs/loader.js:979:16)
[test:acceptance]     at Module._compile (internal/modules/cjs/loader.js:1027:27)
[test:acceptance]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[test:acceptance]     at Module.load (internal/modules/cjs/loader.js:928:32)
[test:acceptance]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[test:acceptance]     at Module.require (internal/modules/cjs/loader.js:952:19)
[test:acceptance]     at require (internal/modules/cjs/helpers.js:88:18)
[test:acceptance]     at /Users/ruwang/workcenter/serenity-js_v3/examples/protractor-cucumber/node_modules/@cucumber/cucumber/src/api/support.ts:28:30
[test:acceptance]     at Array.map (<anonymous>)
[test:acceptance]     at getSupportCodeLibrary (/Users/ruwang/workcenter/serenity-js_v3/examples/protractor-cucumber/node_modules/@cucumber/cucumber/src/api/support.ts:28:16)
[test:acceptance] [18:45:34] E/launcher - Process exited with error code 100
[test:acceptance] npm ERR! code ELIFECYCLE
[test:acceptance] npm ERR! errno 100
[test:acceptance] npm ERR! @examples/protractor-cucumber@3.0.0 test:acceptance: `protractor ./protractor.conf.js`
[test:acceptance] npm ERR! Exit status 100
[test:acceptance] npm ERR! 
[test:acceptance] npm ERR! Failed at the @examples/protractor-cucumber@3.0.0 test:acceptance script.
[test:acceptance] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[test:acceptance] 
[test:acceptance] npm ERR! A complete log of this run can be found in:
[test:acceptance] npm ERR!     /Users/ruwang/.npm/_logs/2023-02-03T23_45_34_563Z-debug.log
[failsafe] Script 'test:acceptance' exited with code 100
```

Indeed, in my personal project with 2.33.10, it doesn't have the same problem. All is fine.

What's more, I tried the 'examples/protractor-mocha' and 'examples/protractor-jasmine' etc, all is fine as well.

I'm running the test on Mac OS Ventura 13.1, Node v14.15.3. 

Please let me know if anything I can do on my end. 

Thank you so much!

**Comment by jan-molak** [comment]
Hi @lucieneven! Thanks, nice catch, I can reproduce it.
It's a typo in the `protractor.conf.js` file: instead of `require-module` it should be `requireModule`:

```diff
    cucumberOpts: {
        require: [
            'features/step_definitions/**/*.ts',
            'features/support/setup.ts',
        ],
-        'require-module': ['ts-node/register'],
+        'requireModule': ['ts-node/register'],
    },
```

Would you like to submit a pull request? Here's the [contributing guide for Serenity/JS 3.0](https://github.com/serenity-js/serenity-js/blob/main/documentation/serenity-js.org/src/pages/contributing.mdx).

Thanks again for reporting the issue!
