### ISSUE TITLE
Wait.until polling issue when using Text.ofAll() using WebdriverIO

### ISSUE THREAD

**Issue by atidyshirt** [serenity-js/serenity-js#1517]
Hi there, @jan-molak @viper3400, I have seen this issue that may be related to this issue here, #1339, I am wondering if `ListItemNotFoundError` error should be thrown in the below case? 

In the below example, we are getting the text of a set of elements and making a comparison. It appears there can be a state when using `Text.ofAll` where Serenity can catch an error from WebdriverIO where the element is not found to get the text of and then Serenity will stop polling as there is no `ListItemNotFoundError` thrown.

**Outline of the Experienced issue:**

In the `waitUntil` function, there seems to be a case that can be hit where the element is not found by WebdriverIO and there is no `ListItemNotFoundError` thrown by Serenity to be caught in the `waitUntil` function when using `Text.ofAll(PageElements)`.

In the below debug, we can see that we cannot call `getElementText` on the object as it does not yet exist. However this is before the `Wait.until`/`Wait.upTo(Duration.ofSeconds(30)).until(...)` has timed out, if the first polling iteration hits this error where the element cannot be found within the webdriverIO polling timeout, then Serenity will hit the `try/catch` block and check for the `ListItemNotFoundError` which instead receives `Error` and stops polling.

**Expected result:**

I would expect that we would throw a `ListItemNotFoundError` when checking the `Text.ofAll` and catching the error thrown from WebdriverIO when trying to get the text from an element that is not present and for this to be caught in the `waitUntil` function in order to continue polling until the timeout is hit.

**Debug, code and output:**

For context I have added some debug to the `waitUntil` method and WebdriverIO's `implicitWait` method in the following manor to more clearly outline the issue:

```javascript
    1 function waitUntil(expectation, pollingInterval) {
    2     let delay;
    3     let pollingActive = false;
    4     async function poll() {
    5     │   async function nextPollingInterval() {
    7     │   │   if (pollingActive) {
    8     │   │   │   delay = waitFor(pollingInterval);
    9     │   │   │   await delay.start();
   10     │   │   │   await poll();
   11     │   │   }
   12     │   }
   13     │   try {
   14     │   │   const expectationIsMet = await expectation();
   15     │   │   console.log("SERENITY:CORE.expectationIsMet", expectationIsMet);
   16     │   │   if (expectationIsMet) {
   17     │   │   │   delay === null || delay === void 0 ? void 0 : delay.stop();
   18     │   │   │   return;
   19     │   │   }
   20     │   │   await nextPollingInterval();
   21     │   }
   22     │   catch (error) {
   23     │   │   console.log("--------- HIT TRY CATCH BLOCK -----------");
   24     │   │   console.log(`SERENITY:CORE.waitUntil.catch`, error);
   25     │   │   delay === null || delay === void 0 ? void 0 : delay.stop();
   26     │   │   if (error instanceof errors_1.ListItemNotFoundError) {
   27     │   │   │   console.log("SERENITY:CORE.waitUntil.catch.instanceOfListItemNotFoundError: ", error);
   28     │   │   │   await nextPollingInterval();
   29     │   │   │   return;
   30     │   │   }
   31     │   │   throw error;
   32     │   }
   33     }
```

**Here is the output from the debug:**

```
[0-0] WEBVDRIVERIO:CORE.implicitWait Error: element ("search-table [row-id] [col-id="nodeName"]") still not existing after 5000ms
[0-0]     at /home/jordanp/vistamanager/test/node_modules/webdriverio/build/commands/browser/waitUntil.js:66:23
[0-0]     at async Element.wrapCommandFn (/home/jordanp/vistamanager/test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.elementErrorHandlerCallbackFn (/home/jordanp/vistamanager/test/node_modules/webdriverio/build/middlewares.js:24:32)
[0-0]     at async Element.wrapCommandFn (/home/jordanp/vistamanager/test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.wrapCommandFn (/home/jordanp/vistamanager/test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.elementErrorHandlerCallbackFn (/home/jordanp/vistamanager/test/node_modules/webdriverio/build/middlewares.js:24:32)
[0-0]     at async Element.wrapCommandFn (/home/jordanp/vistamanager/test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async implicitWait (/home/jordanp/vistamanager/test/node_modules/webdriverio/build/utils/implicitWait.js:18:13)
[0-0]     at async /home/jordanp/vistamanager/test/node_modules/webdriverio/build/utils/refetchElement.js:29:16
[0-0]     at async Element.elementErrorHandlerCallbackFn (/home/jordanp/vistamanager/test/node_modules/webdriverio/build/middlewares.js:41:37)
[0-0] --------- HIT TRY CATCH BLOCK -----------
[0-0] SERENITY:CORE.waitUntil.catch Error: Can't call getElementText on element with selector "search-table [row-id] [col-id="nodeName"]" because element wasn't found
[0-0]     at implicitWait (/home/jordanp/vistamanager/test/node_modules/webdriverio/build/utils/implicitWait.js:35:19)
[0-0]     at async /home/jordanp/vistamanager/test/node_modules/webdriverio/build/utils/refetchElement.js:29:16
[0-0]     at async Element.elementErrorHandlerCallbackFn (/home/jordanp/vistamanager/test/node_modules/webdriverio/build/middlewares.js:41:37)
[0-0]     at async Element.wrapCommandFn (/home/jordanp/vistamanager/test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.wrapCommandFn (/home/jordanp/vistamanager/test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.elementErrorHandlerCallbackFn (/home/jordanp/vistamanager/test/node_modules/webdriverio/build/middlewares.js:44:28)
[0-0]     at async Element.wrapCommandFn (/home/jordanp/vistamanager/test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.wrapCommandFn (/home/jordanp/vistamanager/test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.elementErrorHandlerCallbackFn (/home/jordanp/vistamanager/test/node_modules/webdriverio/build/middlewares.js:24:32)
[0-0]     at async Element.wrapCommandFn (/home/jordanp/vistamanager/test/node_modules/@wdio/utils/build/shim.js:137:29)
```

**Our code:**

```typescript
   9 export class TableCells {
  10     static cellByIdentifier = (cellIdentifier: string): PageElements =>
  11     │   PageElements.located(By.css(`test-table [col-id="${cellIdentifier}"]`));
  12 }


   1     static deviceNameList(numDevices?: number): QuestionAdapter<string[]> {
   2     │   return numDevices != undefined
   3     │   │   ? Text.ofAll(TableCells.cellByIdentifier('nodeName')).slice(0, numDevices)
   4     │   │   : Text.ofAll(TableCells.cellByIdentifier('nodeName'));
   5     }

  147 cucumber.Then('the following devices will be in the device search results:', async (table) => {
  148     const deviceNameList = DataTable.parseSingleArray(table);
  149     return await actorInTheSpotlight().attemptsTo(
  150     │   Wait.upTo(Duration.ofSeconds(30)).until(
  151     │   │   InventorySearchResults.deviceNameList(),
  152     │   │   containAll(deviceNameList),
  153     │   ),
  154     );
  155 });

│  4 export const containAll = Expectation.define(
│  5     'containsAll',
│  6     'containAll',
│  7     <T>(actualValues: T[], expectedValues: T[]) => expectedValues.every((el) => actualValues.includes(el))
│  8 )
```

**Other notes:**

I may be using some methods incorrectly or not as they have intended to be used here, please let me know if this is the case or if I am missing anything in my understanding here.

**Comment by jan-molak** [comment]
Hey @atidyshirt!

So if I understand correctly, what you're proposing is for `Text.ofAll(...)` to throw `ListItemNotFound` if the list of `PageElements` is _empty_?

Would you mind [proposing a PR](https://github.com/serenity-js/serenity-js/blob/main/documentation/serenity-js.org/src/pages/contributing.mdx) with a failing test so we could see what the solution might be? 

The best test suite to add the new test demonstrating the failure is [`PageElements.patterns.spec.ts`](https://github.com/serenity-js/serenity-js/blob/main/integration/web-specs/spec/screenplay/models/PageElements.patterns.spec.ts)

**Comment by viper3400** [comment]
Hi. Yes, the `ListItemNotFoundError` was just implemented in the [List question](https://github.com/serenity-js/serenity-js/blob/main/packages/core/src/screenplay/questions/List.ts).

And your `InventorySearchResults.deviceNameList()` it not to a `List`, but a `QuestionAdapter` containing a string array. 

I wonder, if it would work if you would try to return the `PageElements` in your `deviceNameList` instead and then call the `Text.ofAll`  directly in the `Then`:

```ts
   1     static deviceNameList(numDevices?: number): PageElements {
   2     │   return numDevices != undefined
   3     │   │   ? TableCells.cellByIdentifier('nodeName')).slice(0, numDevices
   4     │   │   : TableCells.cellByIdentifier('nodeName');
   5     }

  147 cucumber.Then('the following devices will be in the device search results:', async (table) => {
  148     const deviceNameList = DataTable.parseSingleArray(table);
  149     return await actorInTheSpotlight().attemptsTo(
  150     │   Wait.upTo(Duration.ofSeconds(30)).until(
  151     │   │   Text.ofAll(InventorySearchResults.deviceNameList()),
  152     │   │   containAll(deviceNameList),
  153     │   ),
  154     );
  155 });
```

**Comment by atidyshirt** [comment]
Hi @jan-molak, @viper3400, Sorry for the late reply, I have not been able to reproduce this issue using the Serenity-JS templates with the following test, I would expect this to have reproduced the same issue as it meets all the criteria that was present in our code base to cause this issue, however it does not.

This likely means that this is not a problem with Serenity and may be due to some external factors from our code base, If I find a solution to this issue and it seems like someone else could run into this problem I will be sure to update this ticket with the relevant information.

I suspect this could be due to some package versions potentially giving unexpected results or a bug in our application that is not easily manually reproducible.

I will close this issue now and re-open if we find a valid method of reproduction.



<details>
<summary>Test details that we expected to reproduce the issue</summary>

```typescript
            describe('using a polling interval that exceeds the timeout to find the element', () => {
                it(`checks to see that text is found on the second polling interval`, () => {
                    const loaderButton = PageElement.located(By.css('[type="button"]'));
                    const newParagraphs = Text.ofAll(PageElements.located(By.css("p")));
                    return actorCalled('Man').attemptsTo(
                        Navigate.to('/screenplay/interactions/wait/loader.html'),
                        Click.on(loaderButton),
                        Wait.upTo(Duration.ofSeconds(4)).until(
                            newParagraphs, 
                            contain('paragraph rendered that did not previously exist')
                        ).pollingEvery(Duration.ofMilliseconds(500))
                    )
                })
            });
``` 

And altered `loader.html` to look as follows:

```html
<html lang="en">
<body>
<h1 id="status">Not ready</h1>
<input id="load" type="button" value="load" onclick="load(2000)" />
<script>
    function load(delay) {
        document.getElementById('status').textContent = 'Loading...'
        setTimeout(function () {
            const paragraph = document.createElement("p");
            paragraph.innerHTML = "paragraph rendered that did not previously exist";
            document.getElementById("body").appendChild(paragraph);
            document.getElementById('status').textContent = 'Ready!'
        }, delay);
    }
</script>
</body>
</html>
```
</details>
