### ISSUE TITLE
Support Playwright 1.33 & 1.34

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#1717]
Playwright 1.33 introduced [significant changes](https://github.com/microsoft/playwright/commit/b1fdf0bcb6462981dc61b22bbb11792bc538924f) to the inner workings of its native reporters.

As reported by @yaffol on the [Serenity/JS Community Chat](https://matrix.to/#/!WQXwnlWOIMXkKHgmvc:gitter.im/$x57RQdiBk9JH27-PAG27KhLYq7wbYNK2NVBZkkdNMqk?via=gitter.im&via=matrix.org&via=matrix.freyachat.eu), this means that using the [Playwrigt HTML reporter](https://playwright.dev/docs/test-reporters#html-reporter) version 1.33 and above with `@serenity-js/playwright-test` 3.2.1 and below results in the following error: 

```
Error in reporter RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at RawReporter._serializeStep (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:184:33)
    at /Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:176:56
    at Array.map (<anonymous>)
    at RawReporter._serializeResult (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:176:39)
    at /Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:164:43
    at Array.map (<anonymous>)
    at RawReporter._serializeTest (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:164:29)
    at /Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:149:40
    at Array.map (<anonymous>)
    at RawReporter._serializeSuite (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:149:26)
    at /Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:148:42
    at Array.map (<anonymous>)
    at RawReporter._serializeSuite (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:148:28)
    at /Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:148:42
    at Array.map (<anonymous>)
    at RawReporter._serializeSuite (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:148:28)
    at /Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:104:21
    at Array.map (<anonymous>)
    at RawReporter.generateProjectReport (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/raw.js:103:28)
    at /Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/html.js:98:34
    at Array.map (<anonymous>)
    at HtmlReporter.onEnd (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/html.js:96:35)
    at /Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/multiplexer.js:104:115
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Multiplexer.onExit (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/reporters/multiplexer.js:102:45)
    at Runner.runAllTests (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/runner/runner.js:75:5)
    at runTests (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/cli.js:135:138)
    at ji.<anonymous> (/Users/pvale/sc/mycrossref/node_modules/@playwright/test/lib/cli.js:48:7)
```

Playwright 1.33 has also introduced test step reporting in UI mode and the trace viewer that Serenity/JS could leverage:

https://www.youtube.com/watch?v=JeFD6rqDbBo

**Comment by jan-molak** [comment]
Closed by #1716, released in Serenity/JS 3.3.0 🎉
