### ISSUE TITLE
FreeMarker template error when generating reports (only in failed scenario with Examples)

### ISSUE THREAD

**Issue by webdkiwinz** [serenity-js/serenity-js#2448]
### What happened?

My setup: Serenity-js (3.25.0), Cucumber(10.8.0), WDIO(8.39.0) and for reports I use SerenityBDD(4.1.6).

If you have Scenario with 2 examples and one of them is flaky or failing constantly ( we have set cucumberOpts { retry:1} to retry) if one of the example fail, this retries only the failed example.
Then the reports were not full generated, meaning: 
SerenityBDD shows <number> failed, there is not option to see the results. See Screen for reference:
![image](https://github.com/user-attachments/assets/d921cfb6-af50-4cbd-a2d5-6c1de5c52af6)

my example 
`  Scenario Outline: Using username and password to log in
    Given that user has an account to login to my website
    When they log into my website with their account:
      | username   | password   |
      | "username" | "password" |
    Then the dashboard page will appear

    Examples:
      | username | password             |
      | tomsmith | SuperSecretPassword! |
      | foobar   | barfoo               |`
      
      
I do get this huge freemarker error.

[test:report] Jul 16, 2024 3:10:47 PM freemarker.log._JULLoggerFactory$JULLogger error
[test:report] SEVERE: Error executing FreeMarker template
[test:report] FreeMarker template error:
[test:report] The following has evaluated to null or missing:
[test:report] ==> row.result  [in template "freemarker/default.ftl" at line 341, column 43]
[test:report] 
[test:report] ----
[test:report] Tip: It's the step after the last dot that caused this error, not those before it.
[test:report] ----
[test:report] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[test:report] ----
[test:report] 
[test:report] ----
[test:report] FTL stack trace ("~" means nesting-related):
[test:report]   - Failed at: ${row.result}  [in template "freemarker/default.ftl" at line 341, column 41]
[test:report] ----
[test:report] 
[test:report] Java stack trace (for programmers):
[test:report] ----
[test:report] freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
[test:report]   at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
[test:report]   at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
[test:report]   at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
[test:report]   at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
[test:report]   at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:104)
[test:report]   at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
[test:report]   at freemarker.core.Environment.visit(Environment.java:371)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
[test:report]   at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
[test:report]   at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
[test:report]   at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
[test:report]   at freemarker.core.Environment.visit(Environment.java:371)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
[test:report]   at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
[test:report]   at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
[test:report]   at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
[test:report]   at freemarker.core.Environment.visit(Environment.java:335)
[test:report]   at freemarker.core.Environment.visit(Environment.java:341)
[test:report]   at freemarker.core.Environment.visit(Environment.java:341)
[test:report]   at freemarker.core.Environment.process(Environment.java:314)
[test:report]   at net.thucydides.model.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:38)
[test:report]   at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:36)
[test:report]   at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:164)
[test:report]   at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:128)
[test:report]   at net.thucydides.core.reports.html.HtmlTestOutcomeReportingTask.generateReports(HtmlTestOutcomeReportingTask.java:53)
[test:report]   at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:33)
[test:report]   at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:12)
[test:report]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[test:report]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[test:report]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[test:report]   at java.base/java.lang.Thread.run(Thread.java:829)
[test:report] 
[test:report] 15:10:47.879 [pool-3-thread-1] WARN  n.t.m.r.t.FreemarkerReportTemplate - Report generation failed
[test:report] freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
[test:report] ==> row.result  [in template "freemarker/default.ftl" at line 341, column 43]
[test:report] 
[test:report] ----
[test:report] Tip: It's the step after the last dot that caused this error, not those before it.
[test:report] ----
[test:report] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[test:report] ----
[test:report] 
[test:report] ----
[test:report] FTL stack trace ("~" means nesting-related):
[test:report]   - Failed at: ${row.result}  [in template "freemarker/default.ftl" at line 341, column 41]
[test:report] ----
[test:report]   at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
[test:report]   at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
[test:report]   at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
[test:report]   at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
[test:report]   at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:104)
[test:report]   at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
[test:report]   at freemarker.core.Environment.visit(Environment.java:371)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
[test:report]   at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
[test:report]   at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
[test:report]   at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
[test:report]   at freemarker.core.Environment.visit(Environment.java:371)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
[test:report]   at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
[test:report]   at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
[test:report]   at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
[test:report]   at freemarker.core.Environment.visit(Environment.java:335)
[test:report]   at freemarker.core.Environment.visit(Environment.java:341)
[test:report]   at freemarker.core.Environment.visit(Environment.java:341)
[test:report]   at freemarker.core.Environment.process(Environment.java:314)
[test:report]   at net.thucydides.model.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:38)
[test:report]   at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:36)
[test:report]   at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:164)
[test:report]   at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:128)
[test:report]   at net.thucydides.core.reports.html.HtmlTestOutcomeReportingTask.generateReports(HtmlTestOutcomeReportingTask.java:53)
[test:report]   at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:33)
[test:report]   at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:12)
[test:report]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[test:report]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[test:report]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[test:report]   at java.base/java.lang.Thread.run(Thread.java:829)
[test:report] 15:10:47.881 [pool-3-thread-1] ERROR n.t.m.r.t.FreemarkerReportTemplate - Syntax error in report template: The following has evaluated to null or missing:
[test:report] ==> row.result  [in template "freemarker/default.ftl" at line 341, column 43]
[test:report] 
[test:report] ----
[test:report] Tip: It's the step after the last dot that caused this error, not those before it.
[test:report] ----
[test:report] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[test:report] ----
[test:report] 
[test:report] ----
[test:report] FTL stack trace ("~" means nesting-related):
[test:report]   - Failed at: ${row.result}  [in template "freemarker/default.ftl" at line 341, column 41]
[test:report] ----
[test:report]   - Failed at: ${row.result}  [in template "freemarker/default.ftl" at line 341, column 41]
[test:report] 
[test:report] 15:10:47.884 [main] WARN  n.t.c.r.h.HtmlAggregateStoryReporter - Failed to generate report - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to merge template: Failed to process FreeMarker template
[test:report] The following has evaluated to null or missing:
[test:report] ==> row.result  [in template "freemarker/default.ftl" at line 341, column 43]
[test:report] 
[test:report] ----
[test:report] Tip: It's the step after the last dot that caused this error, not those before it.
[test:report] ----
[test:report] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[test:report] ----
[test:report] 
[test:report] ----
[test:report] FTL stack trace ("~" means nesting-related):
[test:report]   - Failed at: ${row.result}  [in template "freemarker/default.ftl" at line 341, column 41]
[test:report] ----
[test:report] net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:38)
[test:report] java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to merge template: Failed to process FreeMarker template
[test:report]   at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[test:report]   at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
[test:report]   at net.thucydides.core.reports.html.Reporter.lambda$generateReportsFor$0(Reporter.java:51)
[test:report]   at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[test:report]   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[test:report]   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[test:report]   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[test:report]   at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[test:report]   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[test:report]   at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[test:report]   at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
[test:report]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[test:report]   at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
[test:report]   at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
[test:report]   at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
[test:report]   at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
[test:report]   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[test:report]   at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[test:report]   at net.thucydides.core.reports.html.Reporter.generateReportsFor(Reporter.java:49)
[test:report]   at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:177)
[test:report]   at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:142)
[test:report]   at net.serenitybdd.cli.reporters.CLIAggregateReportGenerator.generateReportsFrom(CLIAggregateReportGenerator.java:66)
[test:report]   at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:52)
[test:report]   at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
[test:report]   at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
[test:report] Caused by: java.lang.RuntimeException: Failed to merge template: Failed to process FreeMarker template
[test:report]   at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:38)
[test:report]   at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:164)
[test:report]   at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:128)
[test:report]   at net.thucydides.core.reports.html.HtmlTestOutcomeReportingTask.generateReports(HtmlTestOutcomeReportingTask.java:53)
[test:report]   at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:33)
[test:report]   at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:12)
[test:report]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[test:report]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[test:report]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[test:report]   at java.base/java.lang.Thread.run(Thread.java:829)
[test:report] Caused by: net.thucydides.model.reports.templates.TemplateMergeException: Failed to process FreeMarker template
[test:report]   at net.thucydides.model.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:41)
[test:report]   at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:36)
[test:report]   ... 9 common frames omitted
[test:report] Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
[test:report] ==> row.result  [in template "freemarker/default.ftl" at line 341, column 43]
[test:report] 
[test:report] ----
[test:report] Tip: It's the step after the last dot that caused this error, not those before it.
[test:report] ----
[test:report] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[test:report] ----
[test:report] 
[test:report] ----
[test:report] FTL stack trace ("~" means nesting-related):
[test:report]   - Failed at: ${row.result}  [in template "freemarker/default.ftl" at line 341, column 41]
[test:report] ----
[test:report]   at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
[test:report]   at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
[test:report]   at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
[test:report]   at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
[test:report]   at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:104)
[test:report]   at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
[test:report]   at freemarker.core.Environment.visit(Environment.java:371)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
[test:report]   at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
[test:report]   at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
[test:report]   at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
[test:report]   at freemarker.core.Environment.visit(Environment.java:371)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
[test:report]   at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
[test:report]   at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
[test:report]   at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
[test:report]   at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
[test:report]   at freemarker.core.Environment.visit(Environment.java:335)
[test:report]   at freemarker.core.Environment.visit(Environment.java:341)
[test:report]   at freemarker.core.Environment.visit(Environment.java:341)
[test:report]   at freemarker.core.Environment.process(Environment.java:314)
[test:report]   at net.thucydides.model.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:38)
[test:report]   ... 10 common frames omitted
[test:report] 15:10:47.885 [main] WARN  n.t.c.r.h.HtmlAggregateStoryReporter - SOME REPORT PAGES COULD NOT BE GENERATED
[test:report]  * Failed to generate report - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to merge template: Failed to process FreeMarker template
[test:report] The following has evaluated to null or missing:
[test:report] ==> row.result  [in template "freemarker/default.ftl" at line 341, column 43]
[test:report] 
[test:report] ----
[test:report] Tip: It's the step after the last dot that caused this error, not those before it.
[test:report] ----
[test:report] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[test:report] ----
[test:report] 
[test:report] ----
[test:report] FTL stack trace ("~" means nesting-related):
[test:report]   - Failed at: ${row.result}  [in template "freemarker/default.ftl" at line 341, column 41]
[test:report] ----
[test:report] net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:38)
[test:report] 
[test:report] 

### Node.js version

20

### How to reproduce the bug.

 Scenario Outline: Using username and password to log in
    Given that user has an account to login to my website
    When they log into my website with their account:
      | username   | password   |
      | <username> | <password> |
    Then the dashboard page will appear

    Examples:
      | username | password             |
      | tomsmith | SuperSecret123Password! |
      | foobar   | barfoo               |
      
1st example should fail, because password is incorrect.
see above screenshot to see how it would like.

### Serenity/JS version

```shell
3.25.0
I tried on 3.23.2 too
```

**Comment by jan-molak** [comment]
Thanks for reporting, @gvenkatnz5658! Would you be able to fork the template project to create a reproducible example I could debug? Thanks! https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template

**Comment by gvenkatnz5658** [comment]
@jan-molak thanks for getting back to me. Here is the repo: https://github.com/gvenkatnz5658/serenity-js-issue-2448/tree/main.
FYI - When run the test, we expect to see a failure which retries.

![image](https://github.com/user-attachments/assets/66b69c62-d3f9-4c54-877f-2f66077904ab)

**Comment by jan-molak** [comment]
OK, so it seems like the issue is triggered only when an example in a `Scenario Outline` is retried; retries for non-outline scenarios are reported correctly.

I'll need to investigate it.
