### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Failed to make Github request, rate limit reached.

### ISSUE THREAD

**Issue by san-ouadghiri** [serenity-js/serenity-js#274]
Just so you know

```
> webdriver-manager update && serenity update

[15:56:52] I/config_source - curl -o/home/mypath/node_modules/protractor/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[15:56:52] I/config_source - curl -o/home/mypath/node_modules/protractor/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[15:56:52] I/config_source - curl -o/home/mypath/node_modules/protractor/node_modules/webdriver-manager/selenium/gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
(node:15841) UnhandledPromiseRejectionWarning: Error: Failed to make Github request, rate limit reached.
    at Request.req.on.response (/home/mypath/node_modules/protractor/node_modules/webdriver-manager/built/lib/binaries/config_source.js:178:28)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/home/mypath/node_modules/request/request.js:1062:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
(node:15841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[15:56:53] I/update - chromedriver: file exists /home/mypath/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.42.zip
[15:56:53] I/update - chromedriver: unzipping chromedriver_2.42.zip
[15:56:53] I/update - chromedriver: setting permissions to 0755 for /home/mypath/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.42
[15:56:53] I/update - chromedriver: chromedriver_2.42 up to date
[15:56:58] I/update - selenium standalone: file exists /home/mypath/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.14.0.jar
[15:56:58] I/update - selenium standalone: selenium-server-standalone-3.14.0.jar up to date
info: Serenity BDD CLI jar file is up to date :-)


```

**Comment by jan-molak** [comment]
Hey @san-ouadghiri, have a look at the https://github.com/angular/webdriver-manager/issues/307#issuecomment-377684918

You might need to ignore the gecko driver if you don't need it:
`webdriver-manager update --gecko=false`

**Comment by jan-molak** [comment]
I've actually started using the [chromedriver](https://www.npmjs.com/package/chromedriver) module directly instead of going through the `webdriver-manager` module.

Then in my `protractor.conf.js`:
```
exports.config = {

    chromeDriver: require(`chromedriver/lib/chromedriver`).path,
    // ...
}
```

Hope this helps!
Jan

**Comment by marktigno** [comment]
@san-ouadghiri I usual encounter this when Github reaches the request download limit. Try to add `--ignore_ssl` when you do serenity update. :)

**Comment by jan-molak** [comment]
Hey @san-ouadghiri and @marktigno!

I've stopped using the `webdriver-manager` module on my projects and instead use the [`chromedriver`](https://www.npmjs.com/package/chromedriver) and [`geckodriver`](https://www.npmjs.com/package/geckodriver) modules:

```javascript
// protractor.conf.js

exports.config = {
    chromeDriver: require('chromedriver/lib/chromedriver').path,
    geckoDriver: require('geckodriver/lib/geckodriver').path,

    SELENIUM_PROMISE_MANAGER: false,
    directConnect: true,

    // ... other config
};
```

Check them out and let me know what you think!

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:
