### ISSUE TITLE
instability problems on restart browser

### ISSUE THREAD

**Issue by boya678** [serenity-js/serenity-js#284]
why did you use protractor?
is not it better to use webdriver js directly?
protractor presents a lot of instability when restarting the browser between test cases, in the same way serenity js with cucumber when executing 3 scenarios restarting the browser presents the problem of "invalidity driver session id"

**Comment by jan-molak** [comment]
Hi @boya678 and welcome to the Serenity/JS community!

When I first wrote Serenity/JS it seemed like a good idea to delegate the task of managing the browser to a well established framework, such as Protractor. This way I could focus on designing an acceptance testing library instead of solving, what I believed to be, a problem that someone has already solved. 

Serenity/JS is not tied to Protractor, though. If one's so inclined it is possible to design [Protractor-like integration](https://github.com/jan-molak/serenity-js/tree/e2a1d472ee3ac7476f5c138e7ebc6c257f4095bc/packages/serenity-js/src/serenity-protractor) for something like webdriver js, webdriver.io, nightwatch, or any other Selenium library. 
I'm currently working on version [2.0](https://github.com/jan-molak/serenity-js/tree/2.0/packages/) of Serenity/JS, which will make it even easier going forward.

Does this answer your question?

Jan

**Comment by boya678** [comment]
i need to do this for guarantee new driver instance on every scenario:

 this.Given(/^(.*) abre Todolist$/, function (nombre:string) {
        protractor.browser=protractor.browser.forkNewDriverInstance();
        this.stage.theActorCalled(nombre).whoCan(BrowseTheWeb.using(protractor.browser));
        return this.stage.theActorInTheSpotlight().attemptsTo(Navegar.a('http://todomvc.com/examples/angular2/'));
    });

so...... i try to assing a new webdriver instance to  "BrowseTheWeb.using" but only receive protractor.browser, can i use a custom driver equal to serenity in java?

Thank you.

**Comment by boya678** [comment]
this.stage.theActorCalled(nombre).whoCan(BrowseTheWeb.using(new ProtractorBrowser(new protractor.Builder().forBrowser('chrome').build()))); this form.

but, serenity js use protractor properties and get this error.

TypeError: Cannot read property 'skipAngularStability' of undefined
         at runWaitForAngularScript (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\protractor\built\browser.js:448:31)
         at ProtractorBrowser.waitForAngular (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\protractor\built\browser.js:460:16)
         at ElementArrayFinder.getWebElements (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\protractor\built\element.js:153:29)
         at ElementArrayFinder.getWebElements (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\protractor\built\element.js:812:39)
         at ElementArrayFinder.applyAction_ (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\protractor\built\element.js:460:34)
         at ElementArrayFinder.(anonymous function).args [as sendKeys] (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\protractor\built\element.js:91:29)
         at ElementFinder.(anonymous function).args [as sendKeys] (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\protractor\built\element.js:831:22)
         at EnterValue.performAs (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\serenity-js\src\serenity-protractor\screenplay\interactions\enter.ts:41:59)
         at c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\@serenity-js\core\src\screenplay\actor.ts:112:43
         at <anonymous>
     From: Task: <anonymous>
         at World.stepWrapper (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:72:18)
         at World.stepWrapper (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\serenity-js\src\serenity-cucumber\webdriver_synchroniser.ts:104:32)
         at World.arity1 (eval at module.exports (c:\Users\721945\CursoAvanzadoProtractor\todoListBDD\node_modules\util-arity\arity.js:22:24), <anonymous>:3:41)
         at _combinedTickCallback (internal/process/next_tick.js:131:7)
         at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by jan-molak** [comment]
Hi @boya678 

Serenity/JS version 2 is live and addresses the issues related to restarting the browser between the tests, as [demonstrated here](https://github.com/serenity-js/serenity-js/blob/af2d4b530765574119ae0b70c49bca4f67f0d22a/integration/protractor-jasmine/spec/restarting_browser_between_tests.spec.ts).

Please check out the [template project](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) and let me know what you think!

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:
