### ISSUE TITLE
Error: using tsconfig-paths with serenity v2

### ISSUE THREAD

**Issue by abhinaba-ghosh** [serenity-js/serenity-js#510]
Hi @jan-molak 

I am using tsconfig-paths to make use of relative paths in the import statements. Natively cucumber supports it and I am successfully using it in my non-screenplay protractor serenity setup. But while using the screenplay mechanism I am getting below error:

```
TypeError: cucumber_1.setDefaultTimeout is not a function
    at Object.<anonymous> (C:\Dev Room\Projects\Demo\config\serenity\setup.ts:12:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\Dev Room\Projects\ArcherAPIBDDTests\node_modules\ts-node\src\index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Dev Room\Projects\Demo\node_modules\ts-node\src\index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at supportCodePaths.forEach.codePath (C:\Dev Room\Projects\Demo\node_modules\cucumber\lib\cli\index.js:119:42)
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (C:\Dev Room\Projects\Demo\node_modules\cucumber\lib\cli\index.js:119:22)
    at Cli.run (C:\Dev Room\Projects\Demo\node_modules\cucumber\lib\cli\index.js:141:37)
```

my setup file:

```ts
import { ConsoleReporter } from '@serenity-js/console-reporter';
import { ArtifactArchiver, configure } from '@serenity-js/core';
import { SerenityBDDReporter } from '@serenity-js/serenity-bdd';

import { setDefaultTimeout } from 'cucumber';
import { Actors } from './actors';

configure({
  actors: new Actors(),
  crew: [ArtifactArchiver.storingArtifactsAt('./target/site/serenity'), new SerenityBDDReporter(), ConsoleReporter.forDarkTerminals()]
});

setDefaultTimeout(60 * 1000);

```

and my require statements are confined in a cucumber profile file:

```js
var common = [
  '--require-module ts-node/register ',
  '--require-module tsconfig-paths/register',
  '--project tsconfig.json',
  '--format node_modules/@serenity-js/cucumber',
  '--require ./config/**/*.ts',
  '--require ./test/**/*.ts ',
  '--require ./src/**/*.ts',
  '--format json:target/cucumber_report.json'
].join(' ');

module.exports = {
  default: common
};

```

**Comment by jan-molak** [comment]
Hey @abhinaba1080! I haven't worked with `tsconfig-paths` so am not sure what magic they use under the hood and how it would affect other modules. I use [barrels](https://basarat.gitbook.io/typescript/main-1/barrel) instead.

Does your setup work without the `tsconfig-paths` module? If so, would it also work with the [TS-native `paths`](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) option instead of the custom `tsconfig-paths` module?

**Comment by viper3400** [comment]
@abhinaba-ghosh , this issue is quite old. Have you been able to solve you problem, meanwhile? If not, could you provide some update about your current setup and issues? 

Otherwise, I'd suggest to close this issue.

**Comment by viper3400** [comment]
I guess we can close this issue. Please do not hesitate to raise a new one if the problem still exists. Just in case, please provide an update about your current setup and issues, then.
