### ISSUE TITLE
Restarting protractor browser between tests can cause issues

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#56]
It seems like restarting the protractor browser between tests can cause some issues:
- an unnecessary browser session might get started after the test run is finished - #34, [#43](https://github.com/jan-molak/serenity-js/issues/43#issuecomment-305290396)
- the failing test might not get reported - [#43](https://github.com/jan-molak/serenity-js/issues/43#issue-230821499)

The possible root cause of those issues could be related to:
- angular/protractor#4224 - "restartBrowserBetweenTests should restart test in beforeEach, not afterEach"
- angular/protractor#2001

It would be great to get a reproducible scenario demonstrating this issue.

**Comment by BlacktoBlue** [comment]
This appears to only happen in versions after 1.2.4

**Comment by jan-molak** [comment]
So far it seems like Protractor will kill the browser and spawn a new one after every single test, including the last test, if the `restartBrowserBetweenTests` flag is set to true
This results in an orphaned browser session that's spawned after the suite is executed.

I'm not yet sure if that's a problem with Protractor or how Serenity/JS communicates with the Protractor Runner and Protractor `afterEach` hook. I need to investigate this further.

**Comment by BlacktoBlue** [comment]
While this is getting investigated by the protractor team, is there a way to manually specify a beforeEach and AfterEach in serenity? would it be in the world.ts file?

**Comment by jan-molak** [comment]
You can do this using the standard mechanisms of either of the supported test runners: [Mocha](https://mochajs.org/#hooks) or Cucumber.

Here's [an example](https://github.com/serenity-js/tutorial-from-scripts-to-serenity/blob/2-reports/features/step_definitions/hooks.ts) of using an after hook with cucumber.

**Comment by jan-molak** [comment]
Looks like @darrinholst managed to [work around](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/commit/a8461e09953bae903c73160bf323a97c645bd534) this problem, we'll need something similar...

**Comment by hamber-dick** [comment]
Any Progress on this? We're not able to run more than 2 Cucumber-Testscenarios without this errors:

`(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 40): NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.`

`NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
         at WebDriverError (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\error.js:27:5)
         at NoSuchSessionError (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\error.js:122:5)
         at session_.flow_.promise (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\webdriver.js:856:16)
         at new ManagedPromise (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\promise.js:1067:7)
         at ControlFlow.promise (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\promise.js:2396:12)
         at promise.finally (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\webdriver.js:855:34)
         at promise.then.error (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\promise.js:1590:12)
         at ManagedPromise.invokeCallback_ (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\promise.js:1366:14)
         at TaskQueue.execute_ (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\promise.js:2970:14)
         at TaskQueue.executeNext_ (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\promise.js:2953:27)
         at asyncRun (C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\promise.js:2813:27)
         at C:\Users\s.sander\workspace\connector-client-protractor\contentHubNG.E2E.Tests\node_modules\selenium-webdriver\lib\promise.js:676:7
         at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by BlacktoBlue** [comment]
@hamber-dick I have managed to work around this by setting restart between tests to false and following @jan-molak example posted above on 23rd of June.

**Comment by BlacktoBlue** [comment]
@jan-molak has any progress been made on this?

**Comment by jan-molak** [comment]
@BlacktoBlue - looks like the protractor issues haven't been addressed and I didn't get a chance to look into any workarounds yet. Thoughts and PRs are welcome!

**Comment by rajeshwarp** [comment]
Hi Jan,

Do we have solution for this now or any workaround to proceed In SerenityJS.

**Comment by rajeshwarp** [comment]
@jan-molak : For now do we have any workarounds/suggestion, that we can use with serenity-js

**Comment by jan-molak** [comment]
Version `2.0.1-alpha.107` should address the issue. Let me know what you think!
