### ISSUE TITLE
Error: Error: Tag name should have a property "length" that is greater than 0

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#677]
Hi @jan-molak greetings.

Thank you for always helping with the troubles.

I have a huge stack of feature files(around 120) and am currently undergoing with the 2.0 migration with template protractor-cucumber.

When i specify the feature in conf.js file like ['features/players/remote.feature'] and run, everything gets picked up fast 
and works perfectly.

When i use it as ['features/**/*.feature]
and run protractor protractor.conf, it take a very long time and after opening the browser.. later throws Error: Error: Tag name should have a property "length" that is greater than 0 
at Object.ensure (node_modules\tiny-types\src\ensure.ts)

Please help me here, this issue was not observed in 1.0 Thanks.

Best Regards,
Abhineet Sharma

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax! Could you please paste the entire stack trace, please? That exception is thrown by one of the implementations of the [`Tag`](https://github.com/serenity-js/serenity-js/blob/master/packages/core/src/model/tags/Tag.ts#L23) class, so it would be good to understand which one.

**Comment by AbhineetSharmax** [comment]
Hi @jan-molak ,

Please find the trace.

14:33:09] E/launcher - Error: Error: Tag name should have a property "length" that is greater than 0

    at Object.ensure (D:\Demo\node_modules\tiny-types\src\ensure.ts:31:15)

    at new Tag (D:\Demo\node_modules\@serenity-js\core\src\model\tags\Tag.ts:23:9)

    at new IssueTag (D:\Demo\node_modules\@serenity-js\core\src\model\tags\IssueTag.ts:10:9)

    at D:\Demo\node_modules\@serenity-js\core\src\model\tags\Tags.ts:16:66

    at Array.map (<anonymous>)

    at MatchesRegExp.transformation (D:\Demo\node_modules\@serenity-js\core\src\model\tags\Tags.ts:16:53)

    at MatchesRegExp.MatcherRule.execute (D:\Demo\node_modules\tiny-types\src\pattern-matching\rules\MatcherRule.ts:13:21)

   at StringMatcher.PatternMatcher.else (D:\Demo\node_modules\tiny-types\src\pattern-matching\PatternMatcher.ts:17:71)

    at Function.from (D:\Demo\node_modules\@serenity-js\core\src\model\tags\Tags.ts:17:18)

    at D:\Demo\node_modules\@serenity-js\cucumber\src\gherkin\feature-files\FeatureFileMapper.ts:183:52

    at Array.map (<anonymous>)

    at FeatureFileMapper.tagsFrom (D:\Demo\node_modules\@serenity-js\cucumber\src\gherkin\feature-files\FeatureFileMapper.ts:183:36)   

    at D:\Demo\node_modules\@serenity-js\cucumber\src\gherkin\feature-files\FeatureFileMapper.ts:53:30

    at Array.forEach (<anonymous>)

    at FeatureFileMapper.map (D:\Demo\node_modules\@serenity-js\cucumber\src\gherkin\feature-files\FeatureFileMapper.ts:22:35)

    at EventEmitter.<anonymous> (D:\Demo\node_modules\@serenity-js\cucumber\src\listeners\CucumberEventProtocolAdapter.ts:48:40)       

[14:33:10] E/launcher - Process exited with error code 100

**Comment by jan-molak** [comment]
Ah OK, that's very helpful, thanks.

In Serenity/JS, `@issue:<issue_id>` and `@issues:<id1>,<id2>` have special meaning and are used to identify tickets in your issue tracker (such as JIRA). The error is thrown because the parser expects that the tag always follows a pattern of `@issue` or `@issues` followed by issue id (see the [specs](https://github.com/serenity-js/serenity-js/blob/005a4025ca3b587c2536ae53276696d35828472f/packages/core/spec/model/Tag.spec.ts#L19-L22)). 

I'm guessing that one or more of your `.feature` files use `@issue` instead of `@issue:<issue_id>`, could you please confirm if that's the case and if changing the tag to say `@defect` or `@bug` solves the problem?

Having said that, the parser should either convert `@issue` to a regular tag, or blow up with a more meaningful message.

**Comment by AbhineetSharmax** [comment]
and that was super thank you so much @jan-molak you are a saviour , i was unaware about about the @issue tag conventions. Now its not throwing me this error and running the scenarios perfectly. Hope it helps to others too. 😊
