### ISSUE TITLE
[cucumber-reporting] Java Errors When Running the Example

### ISSUE THREAD

**Issue by benztest** [serenity-js/serenity-js#683]
If anyone could help with the following java error(s) I would greatly appreciate it.

I've tried several various fixes based on similar errors however these have not related to serenity-js and mostly relate to marven, Gradle, etc which I don't believe is related to this repo. 

```
[test:report]
[test:report] > @serenity-js-examples/cucumber-reporting@2.17.1 test:report C:\<SOME_PATH>\serenity-js\examples\cucumber-reporting
[test:report] > serenity-bdd run
[test:report]
[test:report] Spawning: C:/Program Files/Java/jdk-14.0.2/bin/java.exe -Dserenity.compress.filenames=true -DLOG_LEVEL=warn -Dlogback.configurationFile=C:\<SOME_PATH>\serenity-js\examples\cucumber-reporting\node_modules\@serenity-js\serenity-bdd\resources\logback.config.xml -jar node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-2.1.10-all.jar --destination target/site/serenity --features features --source target/site/serenity --project cucumber-reporting
[test:report] -------------------------------
[test:report] SERENITY COMMAND LINE INTERFACE
[test:report] -------------------------------
[test:report] Loading test outcomes from target\site\serenity
[test:report] Writing aggregated report to target\site\serenity
[test:report]
[test:report] WARNING: An illegal reflective access operation has occurred
[test:report] WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/<SOME_PATH>/serenity-js/examples/cucumber-reporting/node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-2.1.10-all.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
[test:report] WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
[test:report] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[test:report] WARNING: All illegal access operations will be denied in a future release
[test:report] java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
[test:report]   at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
[test:report]   at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
[test:report]   at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
[test:report]   at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
[test:report]   at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
[test:report]   at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:209)
[test:report]   at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:107)
[test:report]   at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:85)
[test:report]   at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
[test:report]   at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
[test:report]   at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:74)
[test:report]   at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
[test:report]   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
[test:report]   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
[test:report]   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
[test:report]   at net.serenitybdd.plugins.jira.workflow.ClasspathWorkflowLoader.<clinit>(ClasspathWorkflowLoader.groovy:15)
[test:report]   at net.serenitybdd.plugins.jira.workflow.ClasspathWorkflowLoader$$FastClassByGuice$$72b186d0.newInstance(<generated>)
[test:report]   at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
[test:report]   at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[test:report]   at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[test:report]   at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
[test:report]   at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
[test:report]   at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
[test:report]   at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
[test:report]   at net.serenitybdd.plugins.jira.JiraFileServiceUpdater.<init>(JiraFileServiceUpdater.java:46)
[test:report]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[test:report]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[test:report]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[test:report]   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[test:report]   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[test:report]   at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:782)
[test:report]   at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:724)
[test:report]   at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1396)
[test:report]   at net.serenitybdd.cli.reporters.CLIIssueTrackerUpdater.generateReportsFrom(CLIIssueTrackerUpdater.java:26)
[test:report]   at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:56)
[test:report]   at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
[test:report]   at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
[test:report] Exception in thread "main" java.util.ServiceConfigurationError: net.thucydides.core.reports.JiraUpdaterService: Provider net.serenitybdd.plugins.jira.JiraFileServiceUpdater could not be instantiated
[test:report]   at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:584)
[test:report]   at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:806)
[test:report]   at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:724)
[test:report]   at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1396)
[test:report]   at net.serenitybdd.cli.reporters.CLIIssueTrackerUpdater.generateReportsFrom(CLIIssueTrackerUpdater.java:26)
[test:report]   at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:56)
[test:report]   at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
[test:report]   at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
[test:report] Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
[test:report]   at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33)
[test:report]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[test:report]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[test:report]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[test:report]   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[test:report]   at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124)
[test:report]   at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346)
[test:report]   at java.base/java.lang.Class.newInstance(Class.java:604)
[test:report]   at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.createMetaMethodFromClass(MetaClassRegistryImpl.java:257)
[test:report]   at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:110)
[test:report]   at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:85)
[test:report]   at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
[test:report]   at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
[test:report]   at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:74)
[test:report]   at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
[test:report]   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
[test:report]   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
[test:report]   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
[test:report]   at net.serenitybdd.plugins.jira.workflow.ClasspathWorkflowLoader.<clinit>(ClasspathWorkflowLoader.groovy:15)
[test:report]   at net.serenitybdd.plugins.jira.workflow.ClasspathWorkflowLoader$$FastClassByGuice$$72b186d0.newInstance(<generated>)
[test:report]   at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
[test:report]   at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[test:report]   at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[test:report]   at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
[test:report]   at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
[test:report]   at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
[test:report]   at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
[test:report]   at net.serenitybdd.plugins.jira.JiraFileServiceUpdater.<init>(JiraFileServiceUpdater.java:46)
[test:report]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[test:report]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[test:report]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[test:report]   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[test:report]   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[test:report]   at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:782)
[test:report]   ... 6 more
[test:report] I'm terribly sorry, but something didn't go according to plan.
[test:report] The following process exited with 1: C:/Program Files/Java/jdk-14.0.2/bin/java.exe -Dserenity.compress.filenames=true -DLOG_LEVEL=warn -Dlogback.configurationFile=C:\<SOME_PATH>\serenity-js\examples\cucumber-reporting\node_modules\@serenity-js\serenity-bdd\resources\logback.config.xml -jar node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-2.1.10-all.jar --destination target/site/serenity --features features --source target/site/serenity --project cucumber-reporting

```

Many thanks for any assistance.
Ben

**Comment by jan-molak** [comment]
Hey @benztest! You're right, it feels like an issue with the Serenity BDD CLI module, available at https://github.com/serenity-bdd/serenity-cli. Would you mind adding a ticket there so that it can be tracked and addressed? Thanks!
