### ISSUE TITLE
protractor-jasmine example broken

### ISSUE THREAD

**Issue by manuelfidalgo** [serenity-js/serenity-js#954]
Hi @jan-molak ,
I think there is a problem with protractor-jasmine example since [2.29.8](https://github.com/serenity-js/serenity-js/releases/tag/v2.29.8) <BR>
**Steps to repro**
- Start with a clean repo
- Install dependencies
- Run `npm test` in folder 'serenity-js/examples/protractor-jasmine'
- You get the following error:

```
[test:acceptance] > @serenity-js-examples/protractor-jasmine@2.0.0 test:acceptance
[test:acceptance] > protractor ./protractor.conf.js
[test:acceptance] 
[test:acceptance] [17:45:23] I/launcher - Running 1 instances of WebDriver
[test:acceptance] [17:45:23] I/direct - Using ChromeDriver directly...
[test:acceptance] [17:45:23] E/launcher - Error: /tmp/serenity-js/examples/protractor-jasmine/spec/interactions.spec.ts:1
[test:acceptance] import { Ensure, equals } from '@serenity-js/assertions';
[test:acceptance] ^^^^^^
[test:acceptance] 
[test:acceptance] SyntaxError: Cannot use import statement outside a module
[test:acceptance]     at wrapSafe (internal/modules/cjs/loader.js:988:16)
[test:acceptance]     at Module._compile (internal/modules/cjs/loader.js:1036:27)
[test:acceptance]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
[test:acceptance]     at Module.load (/tmp/serenity-js/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
[test:acceptance]     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
[test:acceptance]     at Module.require (internal/modules/cjs/loader.js:961:19)
[test:acceptance]     at require (internal/modules/cjs/helpers.js:92:18)
[test:acceptance]     at Loader.requireShim [as require_] (/tmp/serenity-js/examples/protractor-jasmine/node_modules/jasmine/lib/loader.js:35:3)
[test:acceptance]     at /tmp/serenity-js/examples/protractor-jasmine/node_modules/jasmine/lib/loader.js:28:12
[test:acceptance]     at new Promise (<anonymous>)
[test:acceptance]     at Loader.load (/tmp/serenity-js/examples/protractor-jasmine/node_modules/jasmine/lib/loader.js:27:12)
[test:acceptance]     at Jasmine._loadFiles (/tmp/serenity-js/examples/protractor-jasmine/node_modules/jasmine/lib/jasmine.js:178:23)
[test:acceptance]     at Jasmine.loadSpecs (/tmp/serenity-js/examples/protractor-jasmine/node_modules/jasmine/lib/jasmine.js:169:14)
[test:acceptance]     at JasmineAdapter.loadSpecs (/tmp/serenity-js/examples/protractor-jasmine/node_modules/@serenity-js/jasmine/src/adapter/JasmineAdapter.ts:106:27)
[test:acceptance]     at JasmineAdapter.load (/tmp/serenity-js/examples/protractor-jasmine/node_modules/@serenity-js/jasmine/src/adapter/JasmineAdapter.ts:87:20)
[test:acceptance]     at /tmp/serenity-js/examples/protractor-jasmine/node_modules/@serenity-js/protractor/src/adapter/ProtractorFrameworkAdapter.ts:49:32
[test:acceptance]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[test:acceptance] [17:45:23] E/launcher - Process exited with error code 100
[failsafe] Script 'test:acceptance' exited with code 100

```
It also happens with my private project: if I update serenity to version >=2.29.8, it breaks. 
On the other hand if I just use ^2.0.0, it uses 2.29.7 and it works, so i guess there is some dependency problem between 2.29.7 and 2.29.8

Please let me know if you need more details.

Thanks!

**Comment by jan-molak** [comment]
Thanks for reporting, let me have a look.

**Comment by jan-molak** [comment]
Thanks @manuelfidalgo, nice catch! The next version should address this issue.

Let me know if you spot anything else!

**Comment by manuelfidalgo** [comment]
thanks a lot! it's working like a charm
